% Auto-generated by cameraCalibrator app on 12-Jan-2023
%-------------------------------------------------------


% Define images to process
numSubsets = 10;
for i=1:numSubsets
    % Get this batch of file names...:
    dirPath = ['/Users/oliverbroadrick/Desktop/glitter-stuff/jan13/' num2str(i)];
    allFiles = dir(dirPath);
    allFiles = allFiles(~ismember({allFiles.name},{'.','..'}));
    for j=1:size(allFiles,1)
        imageFileNames{j} = [allFiles(j).folder '/' allFiles(j).name];
    end

    % Detect calibration pattern in images
    detector = vision.calibration.monocular.CheckerboardDetector();
    [imagePoints, imagesUsed] = detectPatternPoints(detector, imageFileNames);
    imageFileNames = imageFileNames(imagesUsed);
    
    % Read the first image to obtain image size
    originalImage = imread(imageFileNames{1});
    [mrows, ncols, ~] = size(originalImage);
    
    % Generate world coordinates for the planar pattern keypoints
    squareSize = 2.445000e+01;  % in units of 'millimeters'
    worldPoints = generateWorldPoints(detector, 'SquareSize', squareSize);
    
    % Calibrate the camera
    [cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
        'EstimateSkew', true, 'EstimateTangentialDistortion', false, ...
        'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
        'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
        'ImageSize', [mrows, ncols]);
    
    % Show how many of the images were used
    disp(sum(imagesUsed));

    % Save parameters
    camParams = cameraParams;
    camParamsErrors = estimationErrors;
    chardir = ['/Users/oliverbroadrick/Desktop/glitter-stuff/jan13/' num2str(i) '/'];
    save([chardir 'camParamsSkew'], "camParams");
    save([chardir 'camParamsErrorsSkew'], "camParamsErrors");

    %{
    % View reprojection errors
    h1=figure; showReprojectionErrors(cameraParams);
    
    % Visualize pattern locations
    h2=figure; showExtrinsics(cameraParams, 'CameraCentric');
    
    % Display parameter estimation errors
    displayErrors(estimationErrors, cameraParams);
    
    % For example, you can use the calibration data to remove effects of lens distortion.
    undistortedImage = undistortImage(originalImage, cameraParams);
    
    % See additional examples of how to use the calibration data.  At the prompt type:
    % showdemo('MeasuringPlanarObjectsExample')
    % showdemo('StructureFromMotionExample')
    %}
end