function testcases = loadTestCases()

    testcases.wideangle1 = struct('name','Wide Angle Lens (light position off the monitor, chem side)', ...
                'expdir','/Users/oliverbroadrick/Desktop/glitter-stuff/wideAngleCardboard/', ...
                'impath','chem.JPG', ...
                'lightPosFname', 'chemLightPos.mat', ...
                'skew', true, ...
                'sixteen', false);
    testcases.middle = struct('name','Original Camera (Nikonz7 35mm) middle position (light off monitor, chem side)', ...
                'expdir','/Users/oliverbroadrick/Desktop/glitter-stuff/newCamPosNov6_middle/', ...
                'impath','chem.JPG', ...
                'lightPosFname', 'chemLightPos.mat', ...
                'skew', false, ...
                'sixteen', true);
    testcases.iphone1 = struct('name','iPhone XR (light off monitor, chem side)', ...
                'expdir','/Users/oliverbroadrick/Desktop/glitter-stuff/iphone/', ...
                'impath','chem.JPG', ...
                'lightPosFname', 'chemLightPos.mat', ...
                'skew', true, ...
                'sixteen', true);
    for index=1:10
        testcases.jan12(index) = struct('name',['Nikon Z7 (January 12 Data) Position ' num2str(index)], ...
                    'expdir','/Users/oliverbroadrick/Desktop/glitter-stuff/jan12/', ...
                    'impath',[num2str(index) '.JPG'], ...
                    'lightPosFname', ['lightPos' num2str(num2str(index)) '.mat'], ...
                    'skew', true, ...
                    'sixteen', true, ...
                    'numLightPositions', 10);
    end
    for index=1:10
        testcases.jan13(index) = struct('name',['Nikon Z7 (January 13 Data) Position ' num2str(index)], ...
                    'expdir','/Users/oliverbroadrick/Desktop/glitter-stuff/jan13/', ...
                    'impath',[num2str(index) '.JPG'], ...
                    'lightPosFname', ['lightPos' num2str(num2str(index)) '.mat'], ...
                    'skew', true, ...
                    'sixteen', true, ...
                    'numLightPositions', 10);
    end
end