function testcases = loadTestCases()
    for i=1:10
        testcases.mar4tests(i) = struct('name',['Testing the new board (light position ' num2str(i) ')'], ...
                    'expdir','/Users/oliverbroadrick/Desktop/glitter-stuff/mar4tests/', ...
                    'impath',[num2str(i) 'a.JPG'], ...
                    'lightPosFname', ['lightPos' num2str(i) '.mat'], ...
                    'skew', true);
    end
end