function testcases = loadTestCases()
    for i=1:10
        testcases.mar4tests(i) = struct('name',['Testing the new board (light position ' num2str(i) ')'], ...
                    'expdir','/Users/oliverbroadrick/Desktop/glitter-stuff/mar4tests/', ...
                    'impath',[num2str(i) 'a.JPG'], ...
                    'lightPosFname', ['lightPos' num2str(i) '.mat'], ...
                    'skew', true);
    end
    for i=1:6
        testcases.ICCV_camPos1(i) = struct('name',['ICCV_camPos1 lightPos' num2str(i)], ...
                    'expdir','/Users/oliverbroadrick/Desktop/glitter-stuff/ICCV_camPos1/', ...
                    'impath',[num2str(i) '.JPG'], ...
                    'lightPosFname', ['lightPos' num2str(i) '.mat'], ...
                    'skew', true);
    end
    for i=1:6
        testcases.c1(i) = struct('name',['c1 lightPos' num2str(i)], ...
                    'expdir','/Users/oliverbroadrick/Desktop/glitter-stuff/c1/', ...
                    'impath',[num2str(i) '.JPG'], ...
                    'lightPosFname', ['lightPos' num2str(i) '.mat'], ...
                    'skew', true);
    end
    for i=1:6
        testcases.c2(i) = struct('name',['c2 lightPos' num2str(i)], ...
                    'expdir','/Users/oliverbroadrick/Desktop/glitter-stuff/c2/', ...
                    'impath',[num2str(i) '.JPG'], ...
                    'lightPosFname', ['lightPos' num2str(i) '.mat'], ...
                    'skew', true);
    end
end